title: Rita的个人博客 
author: Rita
description: Rita的个人博客。分享工作中的相关知识。此外还输出自己的思考内容等。
baseurl: "" 
url: "https://ruoye123.github.io"
social:
  name: Rita
  links: https://github.com/ruoye123

permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

