#Dependencies
markdown: kramdown
highlighter: rouge

#Setup
title: Rita的个人博客 
description: >-#
   Rita的个人博客。分享工作中的相关知识。此外还输出自己的思考内容等。
baseurl: "" 
url: "https://ruoye123.github.io"
repository:rita

author:
  name: Rita
  url: https://twitter.com/BenBalter

permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
